# This workflow will build and generate the distribuition
name: "Tagged Release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn package -DskipTests -Dmaven.test.skip=true -Pdocs-gen,distribuition -B --file pom.xml
    - name: Release Binary
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        #automatic_release_tag: "latest"
        title: "Latest Build"
        prerelease: false
        files: |
          docs/*.html
          openldap-jldap/target/*.jar
          openldap-dsml-common/target/*.jar
          openldap-dsml-streaming/target/*.war
